### ISSUE TITLE
String getting precomputed and thus not obfuscated

### ISSUE THREAD

**Issue by dcam0050** [jeromer/mumbojumbo#1]
Hi there! I was testing out this package and incorporating the generated code within a go package however upon building noticed that the string is still discoverable when running strings and stored in plaintext format in the binary. 

It seems like with certain compiler optimisations will precompute the generated code due to the variable used is a const.

I solved it by defining eax within the function block as a var instead of a const and the string is then computed at runtime and does not show up when running strings on the binary

**Comment by jeromer** [comment]
Hi there !

For some reason I did not get an email about this issue :/

Could you please provide a patch in a PR so everyone else can benefit of your solution ?

Thanks :)

**Comment by jeromer** [comment]
1d65b6738020ef8be313384c27d6ed662a6ed16c should fix the issue.
